encoding: UTF-8
# Site settings
title: Mr. de Jong
email: mrdejong89@gmail.com
description: "This is my personal on github pages. You'll find all my latest projects here."
baseurl: ""
url: "http://mrdejong.github.io"

# Build settings
markdown: kramdown
permalink: pretty

gems: [jekyll-sass]

# Sass settings
sass:
  sass_dir: css